dials/data

- dials_data/definitions/centroid_test_data.yml
for remaining dials test.
dxtbx adds a few more `.pickle` files from the directory, but I haven't added them yet as they compress exceedingly well (>90 MB -> <15 kB), so I'll want to work on #12 first.
> Add centroid_test_data/sweep.json

- dials_data/definitions/l_cysteine_4_sweeps_scaled.yml
Add definition for recently scaled l-cysteine data for testing post-scaling dials programs e.g dials.export, dials.merge etc.
> Add definition for datafiles of four scaled sweeps of L-cysteine

- dials_data/download.py
and if it is not then set the `DataFetcher` instance to read-only.
Drop unused keyword argument `target_dir`.
Fixes case on Jenkins where builds on MacOS can not (and will never be able to) download the test data into the shared location.
> Check data repository is writable

- dials_data/definitions/centroid_test_data.yml
These files are used in dxtbx for centroid_test_data related tests.
> Add further files for dxtbx tests

- dials_data/definitions/lysozyme_electron_diffraction.yml
- dials_data/definitions/simulated_lysozyme.yml
Following from my comments in #83 this is what I would propose:
1. rename the dataset to something descriptive of the dataset (`simulated_lysozyme`), rather than something describing the intended use you have for it (`dials-for-ed`).
Other people can get a list of datasets included in dials.data by running `dials.data list`. We should not specify what the data can be used for, or even how we intend to use it. Just be clear about what the data are and where they come from, and then other people (including future-us) will find uses for the data.
2. In that vein - if we had any more information on where the data come from (Simulated how? Is the simulated dataset available? Are the instructions that were used to simulate the dataset available? How was it processed? Commands? Versions?) that …
> Rename dials-for-ed dataset

- .dependabot/config.yml
limit dependency updates to 2.7-compatible packages
> We still support Python 2.7

- dials_data/definitions/l_cysteine_dials_output.yml
Some experiment list files in https://github.com/dials/dials-data used to use relative paths (pointing to a location on @graeme-winter's computer) and incorrect file extensions for the image files to which they refer.  This PR points to the fixed files.
> Use fixed experiment list files

- dials_data/definitions/image_examples.yml
Add single-image Eiger test data in Dectris' standard nearly-NeXus format.
Details of these semi-synthetic data are kept in the repository where the files are stored:
https://github.com/dials/data-files/tree/master/image_examples
> Add Dectris Eiger single-image test data

- .dependabot/config.yml
until September when Python 3.5 is EOL.
Closes #164
> Stick with older version of mock

- dials_data/definitions/l_cysteine_dials_output.yml
At the moment, these are links from dials/data-files, but in the future
they can be links from Zenodo, see #172.
> Add links to l-cysteine image data

- dials_data/definitions/l_cysteine_dials_output.yml
This is particularly useful for testing the behaviour of DIALS programs with few reflections.
Are there any objections to including these data in `l_cysteine_dials_output.yml`?  Does that clutter things somewhat?
> Include narrow-wedge integrated test data

- dials_data/definitions/l_cysteine_dials_output.yml
Add some more CBFs to `l_cysteine_dials_output`.
These turn out to be necessary for some minimal xia2 multiple-sweep tests.
> Add five more CBFs per sweep of a four-sweep set

- dials_data/definitions/l_cysteine_dials_output.yml
`.expt` files referred to a `/home/...` directory, which is not accessible,
leading to errors when loading the experiments. This changes the file
reference to be relative and removes the mask reference entirely.
> remove absolute paths from l-cysteine-dials-output

- dials_data/definitions/spring8_ccp4_2018.yml
- dials_data/download.py
Two alternative implementations of adding tarfile support:
1. Decompress tarfiles immediately after downloading, before validation of the downloaded file (17484f2)
2. Require a list of expected tar file contents to be defined in the definition.yml. After validation of the downloaded tarfile, then check the whether all expected files `source["files"]` exist locally, and if not, decompress the tarfile (0429b7e)
Minimal definition for 1. would be:
```
data:
- url: https://zenodo.org/record/1443110/files/ccp4school2018_bl41xu_data03.tar.xz
```
Whereas for 2. more information is required:
```
data:
- url: https://zenodo.org/record/1443110/files/ccp4school2018_bl41xu_data03.tar.xz
files:
- ccp4school2018_bl41xu/05/data03/data03_master.h5
- ccp4school2018_bl41xu/05/data03/data03_data_000001.h5
- …
```
> Add tarfile support

- dials_data/cli.py
Changes output of `dials.data --help` like this:
```patch
usage: dials.data <command> [<args>]
DIALS regression data manager v2.1.12-g589a0f7
The most commonly used commands are:
list     List available datasets
get      Download datasets
+
+Each command has its own set of parameters, and you can get more information
+by running dials.data <command> --help
optional arguments:
-h, --help  show this help message and exit
```
> Hint that every command provides individual --help

- requirements_dev.txt
- tests/test_dials_data.py
We don't use any features that are not already part of the 3.6+ standard library version
Closes #228
> drop mock dependency

- dials_data/download.py
The used Windows library call waits only up for a maximum of about 10 seconds and then raises a 'Resource deadlock avoided' exception. This pull request adds the necessary so we can wait indefinitely for a lock.
> Don't crash out when waiting for download file lock on Windows

- README.rst
- dials_data/download.py
- docs/installation.rst
- tests/test_dials_data.py
Instead of providing `py.path.local()` objects add a facility to provide
`pathlib.Path()` objects.
Update tests and the documentation accordingly.
Don't add a `DeprecationWarning` yet for backward compatibility with older
`dials_data` versions installed on developer machines.
> Start supporting pathlib.Path() objects

- docs/installation.rst
Apparently don't use `::` before code blocks
> fix documentation ReST syntax

- dials_data/definitions/image_examples.yml
- dials_data/definitions/pycbf.yml
Add the pycbf test files. This includes a sample mar345 image, which has been added to the image_examples definition.
> Add pycbf test data

- .bumpversion.cfg
- HISTORY.rst
- dials_data/__init__.py
- dials_data/download.py
- docs/conf.py
- docs/installation.rst
- setup.cfg
- tests/test_dials_data.py
`py.path` has been deprecated (rather: ["_in maintenance mode_"](https://py.readthedocs.io/en/latest/path.html)) for a long time, and since we moved to Python 3 there is no reason now to not use the standard library [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) objects.
This commit enables a `DeprecationWarning` when the pytest fixture does not specify a preferred return object type.
A deprecation plan is laid out in `HISTORY.rst`
> Begin deprecation of `py.path` usage

- .bumpversion.cfg
- dials_data/__init__.py
- docs/conf.py
- setup.cfg
Minor version increase because of Python 3.6 EOL and dataset rename
> Bump version: 2.2.0 → 2.3.0

- dials_data/download.py
Unless I'm mistaken, this looks like the intended method call.  @Anthchirp, I'm not sure exactly what this does, nor how to test for the correct behaviour.
> Correct typo in pathlib.Path.is_file method call

- dials_data/download.py
- tests/test_dials_data.py
this is redundant, as this is the target directory (when read-only=False) or nothing (when read-only=True)
> Remove 'lockdir' parameter

- dials_data/definitions/four_circle_eiger.yml
A new version of this data set has been uploaded to Zenodo.  In this new
version, the data set `/entry/instrument/detector_distance` has been
renamed to `/entry/instrument/detector/distance`.
> Update data set four_circle_eiger to match Zenodo

- dials_data/definitions/four_circle_eiger.yml
Yet another new version of this data set has been uploaded to Zenodo.  In the previous version, the file paths within the `*.tar.xz` archives included a superfluous top-level `./` directory.  This version removes the `./` portion of the paths.
> Update data set four_circle_eiger again :disappointed:

- dials_data/definitions/cunir_serial.yml
Required for testing data reduction workflows for SSX data
> Add reference PDB model to cunir_serial definition

- dials_data/definitions/dtpb_serial_processed.yml
This PR adds integrated data files from `xia2.ssx` processing of two VMXi serial grid scans.
The purpose is to enable testing of data reduction features on processed data originating from images in nexus/h5 format (in addition to existing tests on cbf format).
> Add example integrated files from vmxi serial grid scans on DtpB.

- dials_data/definitions/refinement_test_data.yml
This moves derived processing files used by DIALS refinement tests (and some others) into `dials_data` to reduce reliance on the private `dials_regression` repository.
> Add refinement_test_data, copied from dials_regression

- CONTRIBUTING.rst
- README.rst
- docs/installation.rst
- docs/why.rst
Replaced documentation references to package name `dials_data` with `dials-data` for consistency (`dials_data` is not recognised on conda). I've left references to directories and github paths as `dials_data`. Pytest fixture is also `dials_data`. I now remember why I didn't commit to pushing this earlier.
> dials_data is repo name dials-data is package name

- HISTORY.rst
- dials_data/download.py
If the creator saved uid/gid/permissions into the tar archive, this could cause a warning (not being able to set uid/gid), but could also overwrite the intended permissions of the destination path with those inside the archive.
This cause an issue at Diamond where one of the data sets encoded `0o660` instead of inheriting from the directory `0o664`, which meant the data was not accessible by other users.
> Don't use permission flags from tar archives

- dials_data/definitions/centroid_test_data.yml
- dials_data/definitions/refinement_test_data.yml
Update to newer versions of two experiment files and add an `ExperimentList` to replace a deprecated `DataBlock`
See https://github.com/dials/data-files/pull/48
> Update obsolete files

- requirements_doc.txt
sphinx_rtd_theme is currently incompatible with sphinx 7.
Renovate doesn't care. It just blindly updates. We may need to reconsider using this tool.
> Downgrade sphinx that renovate broke

- dials_data/definitions/semisynthetic_multilattice.yml
This adds prcoessed data for the purpose of testing indexing - it contains two different sweeps, each containing two crystal lattices, so is useful for testing the most generalised case of multiple imagesets + multiple lattices per imageset.
> Add semisynthetic multilattice data for testing indexing

- setup.cfg
Avoid downstream CI errors caused by https://github.com/python/importlib_resources/issues/298
> Pin importlib_resources to avoid CI errors

- dials_data/definitions/isis_sxd_nacl_processed.yml
Adds `isis_sxd_nacl_processed.yml` as an example of processed time-of-flight data.
> add isis_sxd_nacl_processed.yml

- dials_data/definitions/image_examples.yml
3 images from CXI.DB entry 221, https://cxidb.org/id-221.html
Images reformatted as NeXus NXmx format by Takanori Nakane, including parameter data_scale_factor, which accounts for a gain of 10
> Add MPCCD images reformatted as NeXus NXmx

- dials_data/definitions/image_examples.yml
- dials_data/definitions/indexing_test_data.yml
A few DIALS processing files used in indexing tests, plus one I23 image file used in various other tests. These have come from dials_regression, full provenance now unknown.
> Extend indexing and image test files

- dials_data/definitions/i04_weak_data.yml
Adds the i04_weak_data files used in various DIALS tests
> i04_weak_data

- dials_data/definitions/insulin_processed_xds_1.yml
- dials_data/definitions/insulin_processed_xds_2.yml
Will be used for testing `dials.import_xds` and `xia2.multiplex`.
Need to be as two separate definitions so that each will be in a separate directory in dials.data, as `dials.import_xds` works by filename matching by default, and this is also how processed data comes out of xia2.
> Add example integrated XDS data files

- dials_data/definitions/indexing_test_data.yml
Add definitions of data files for testing indexing routines from two more datasets. Beta lactamase (c2sum tutorial dataset) is a well diffracting sample and ins14_24 is a commissioning insulin dataset which is poor quality/noise and representative of an unsuccessful collection. Reflection data files are HDF5 format.
> Add two more indexing test datasets.
