dials/data

dials_data/definitions/insulin.yml
name: Insulin
author: John Cowan (2006)
url: https://xia2.github.io/insulin_tutorial.html
description: 45 degree insulin dataset for testing and training purposes.
Used in tests in dials and xia2
=> Add insulin dataset

HISTORY.rst, README.rst, dials_data/__init__.py, docs/conf.py, requirements_dev.txt, setup.cfg, setup.py, tox.ini
and add a test to identify these problems before deployment.
=> Fix PyPI readme

.travis.yml, .travis/reset-repository, .travis/update-hashinfo, .travis/update-package-version, requirements.txt, setup.py, tox.ini
Rework Travis scripts
Enable builds for Python 3.8
Fixes #13
=> Automatically deploy every successful build (#13)

dials_data/definitions/multi_crystal_proteinase_k.yml
used in xia2 regression testing. Adding this resolves SCI-8254.
=> Add multi-crystal-proteinase-k dataset

dials_data/definitions/l_cysteine_dials_output.yml
=> Add l-cysteine test files

dials_data/download.py
In cases where the user does not have write permissions to the target
directory (ie. a shared repository) then only acquire a download lock
when files need to be written.
=> Acquire the download lock as late as possible

dials_data/download.py
ie. don't crash when header not there.
=> Tolerate missing Content-Length headers

dials_data/definitions/centroid_test_data.yml
See https://github.com/dials/data-files/pull/1
=> Mask file contains flex.bool, it should contain tuple of flex.bool

dials_data/cli.py
giving the machine-readable path to the data files.
Fixes #55
=> Add -q option to dials.data get for terse output

setup.py
makes repository discoverable by libtbx.precommit
=> Enable precommits for dials-data repository

tests/test_yaml_files.py
=> minor code cleanup

dials_data/definitions/dials_for_ed.yml
Useful for testing ED analysis tools such as dials.plot_Fo_vs_Fc
=> Definition for a refined MTZ from ED.

dials_data/definitions/smv_image_examples.yml
These can be used to exercise the following SMV Format classes:
- FormatSMVJHSim
- FormatSMVTimePix_SU_512x512
- FormatSMVTimePix_SU_516x516
=> Add definition for 3 SMV files for Format class testing

dials_data/definitions/image_examples.yml
Intended to be a collection of miscellaneous test images, primarily for testing individual format classes.
=> New image_examples dataset

dials_data/definitions/thaumatin_eiger_screen.yml
=> Rename + words

dials_data/definitions/image_examples.yml
origin commit was squashed/rebased, so received a new commit ID
=> fix commit ID

dials_data/definitions/x4wide.yml, dials_data/definitions/x4wide_processed.yml
AUTOMATIC_DEFAULT_scaled.expt
AUTOMATIC_DEFAULT_scaled.refl
AUTOMATIC_DEFAULT_scaled.mtz
AUTOMATIC_DEFAULT_scaled_unmerged.mtz
Generated by running `xia2 image=$(dials.data get -q x4wide)/X4_wide_M1S4_2_0001.cbf`
=> add scaled output for x4wide dataset

dials_data/definitions/l_cysteine_dials_output.yml
- dials 2.X-style naming
- New spotfinding algorithm output
- Include output of dials.index
=> Updated l_cysteine_dials_output

dials_data/download.py
Bug found and fixed by Charles Ballard
=> Fix file locking for Windows

dials_data/definitions/l_cysteine_dials_output.yml
data from xia2/xia2#28, used in post-integration dials regression tests
=> add the xia2-28 file set

dials_data/definitions/thaumatin_grid_scan.yml
for stills testing.
The `author:` line is missing
=> Add thaumatin grid scan

requirements_dev.txt, setup.py
=> pytest-runner no longer needed

dials_data/definitions/l_cysteine_dials_output.yml
Ugh, copy-paste error last time.  This does basically what #162 (with #163) was supposed to do.  But this time, I'm pretty sure it does it right.
=> Correct another reference in an experiment list file

dials_data/cli.py
which allows machine-readable extraction of version information and
repository location (and possibly more in the future)
Should be useful for build pipelines
=> Add a 'dials.data info' command

.travis/update-package-version
account for PEP-517/518 changes
=> Update travis package version updater

.dependabot/config.yml, requirements.txt, requirements_dev.txt
Resolves #197
Closes #198
Resolves #200
Resolves #201
=> Update dependencies and dependabot configuration

dials_data/definitions/relion_tutorial_data.yml
Need to retain the directory structure of the tutorial data (#205)
At the moment this is only possible by packing it up.
=> Pack up relion tutorial data

dials_data/definitions/vmxi_thaumatin_grid_index.yml
file was pointing to a local mask file
=> Remove invalid mask reference from dataset

.github/dependabot.yml, .travis.yml, README.rst, setup.cfg, tox.ini
3.5 has reached [end of support](https://www.python.org/downloads/)
=> Drop Python 3.5 support

.travis.yml, dials_data/cli.py, dials_data/datasets.py, requirements.txt, requirements_dev.txt
* python-3.9
* f-strings
* dependabot/pip/pytest-6.1.2
* dependabot/pip/tox-3.20.1
* dependabot/pip/pip-20.2.4
* dependabot/pip/bump2version-1.0.1
=> merge all open branches

dials_data/definitions/isis_sxd_example_data.yml
Added isis_sxd_example_data.yml to defintions to allow for tests with SXD data.
=> Added isis_sxd_example_data.yml to defintions

dials_data/definitions/relion_tutorial_data.yml
Add log files to the yaml file list and change the url to point to the `data-files` commit that adds these new files
=> Add log files to relion_tutorial_data

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/ci.yml, .codecov.yml, requirements.txt, requirements_dev.txt
- Update dependencies and Azure build script
- Enable testing on MacOS
- Add codecov.io configuration file
closes #268, closes #269, closes #270, closes #271
=> Update dependencies and build script

dials_data/definitions/relion_tutorial_data.yml
To match the change made in dials/data-files#28
=> Update commit id for Relion tutorial data which now has problematic part of star file removed

dials_data/cli.py
'major' should just be the first component, so add a fixed key now and remove the 'broken' one at some point in the future.
=> Add a new string describing the major+minor version

dials_data/definitions/relion_tutorial_data.yml
Should fix relion_tutorial_data
=> Update relion_tutorial_data url to pick up dials/data-files#29

.azure-pipelines/azure-pipelines.yml, .azure-pipelines/ci-windows.yml, .azure-pipelines/ci.yml, requirements_dev.txt, requirements_doc.txt, tests/test_dials_data.py
Historically we haven't run the tests on Windows. Let's change this.
=> Officially add Windows support

dials_data/definitions/MyD88_processed.yml
See also https://github.com/dials/data-files/pull/33
=> Add definition for MyD88 dataset 1 imported.expt and strong.refl

dials_data/definitions/SSX_CuNiR_images.yml, dials_data/definitions/cunir_serial.yml
This PR adds the images used to create the data files in SSX_CuNiR_processed
=> Add example SSX image data taken at I24, DLS

dials_data/definitions/cunir_serial_processed.yml
Test files were updated so that they can be used with the image data recently uploaded.
=> Point to updated processed data files for cunir_serial_processed

.azure-pipelines/azure-pipelines.yml, HISTORY.rst, pyproject.toml
=> Add Mypy type checking to the CI

HISTORY.rst, dials_data/cli.py, dials_data/datasets.py, dials_data/download.py, dials_data/pytest11.py, tests/test_dials_data.py
and add some type annotation/code modernisation as I go along
=> Start work on eliminating internal use of py.path

CONTRIBUTING.rst
tox is no longer a thing, but pre-commits are
=> Update contribution guidelines

CONTRIBUTING.rst, docs/installation.rst, docs/why.rst
Try to fix slight inconsistency between repo name: `dials/data`, package name: `dials-data`,  and what I assume is and old name `dials_data`.
=> Tweak docs

dials_data/definitions/four_circle_eiger.yml
Add a definition for https://doi.org/10.5281/zenodo.6093230.
=> Add a definition for recent I19-2 Eiger data

dials_data/download.py
so they don't interfere with tests
=> Move lockfiles above dataset directories

CONTRIBUTING.rst, README.rst
I missed the install instruction in README with my previous attempt to standardise `dials-data`
=> change more dials_data to dials-data

dials_data/download.py
Attempts to download files will be retried. A retry attempt will be made on: 
| Code | Meaning |
|------|---------|
| [413](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413)* | Payload too large
| [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)* | Too many requests 
| [500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) | Internal Server Error
| [502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502) | Bad Gateway
| [503](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503)* | Service unavailable
| [504](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) | Gateway Timeout
Through the [`urllib.util.Retry`](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry) class, which …
=> Retry failed connections

dials_data/definitions/insulin_processed.yml
Update paths to [reflect changes](https://github.com/dials/data-files/pull/43) to insulin_processed .expt files.
=> Update paths for insulin_processed .expt files

.github/renovate.json
And avoid lots of pointless noise
Closes #392
Closes #391
Closes #390
Closes #388
Closes #387
Closes #386
=> Disable Azure task updates

dials_data/definitions/multi_crystal_proteinase_k.yml
Add a PDB model to help testing data reduction routines.
=> Add pdb reference file for multi_crystal_proteinase_k

.azure-pipelines/azure-pipelines.yml, .pre-commit-config.yaml, setup.cfg
The pinned isort version had a dependency error.
=> Set minimum python to 3.8. Update pre-commits

dials_data/definitions/i04_weak_data.yml
Used in `test_index.py::test_index_peak_search_clean`
=> Additional i04_weak_data file

dials_data/definitions/centroid_test_data.yml, dials_data/definitions/integration_test_data.yml
Files used for tests of integration code
=> Integration test data

dials_data/definitions/experiment_test_data.yml, dials_data/definitions/shadow_test_data.yml
Adds `shadow_test_data.yml` and `experiment_test_data.yml`
=> Final two data sets of files copied from dials_regression

dials_data/definitions/experiment_test_data.yml
These files were previously missed when making `DIALS_REGRESSION` --> `DIALS_DATA` changes
=> Update to fixed versions of `imageset.json` and `sweep.json`

dials_data/definitions/shadow_test_data.yml
Removed a local file path, and point to the updated file
=> Fix `shadow_test_data`

dials_data/definitions/centroid_test_data.yml
As found by CI tests for https://github.com/cctbx/dxtbx/pull/812
=> Missed this file
